Repository opensearch-project/dashboards-visualizations, pull requests merged in 2023-07, with the labels that each got.

#198 Upgrade tough-cookie to fix CVE-2023-26136
  gantt-chart/package.json
  gantt-chart/yarn.lock
Labels: dependencies, backport 2.x, backport 2.9

#205 Add release notes for 2.9.0
  release-notes/opensearch-dashboards-visualizations.release-notes-2.9.0.0.md
Labels: documentation, backport 2.x, backport 2.9

#218 update semver
  gantt-chart/package.json
  gantt-chart/yarn.lock
Labels: backport 2.x
