Repository opensearch-project/dashboards-visualizations, pull requests merged in 2023-10, with the labels that each got.

#266 Maintenance/release notes 2.11
  release-notes/opensearch-dashboards-visualizations.release-notes-2.11.0.0.md
Labels: backport 2.x, backport main

#287 Onboard jenkins prod docker images to github actions
  .github/workflows/dco.yml
  .github/workflows/release-workflow.yml
  .github/workflows/test-and-build-workflow.yml
Labels: enhancement, backport 2.x

#288 [Backport 2.x] Onboard jenkins prod docker images to github actions
  .github/workflows/dco.yml
  .github/workflows/release-workflow.yml
  .github/workflows/test-and-build-workflow.yml
Labels: enhancement
