Repository opensearch-project/dashboards-visualizations, pull requests merged in 2024-02, with the labels that each got.

#332 Added release notes for 2.12
  release-notes/opensearch-dashboards-visualizations.release-notes-2.12.0.0.md
Labels: backport 2.x, backport 2.12

#335 upgrade plotly to v2
  package.json
  yarn.lock
Labels: dependencies, backport 2.x

#341 [CI/CD] Add single version flag during bootstrap to fix version conflicts
  .github/workflows/cypress-e2e-gantt-chart-test.yml
  .github/workflows/ftr-e2e-gantt-chart-test.yml
  .github/workflows/lint.yml
  .github/workflows/test-and-build-workflow.yml
Labels: backport 2.x
